package com.employees.employees.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

@Data
public class TeamDto {
    @Schema(description = "Unique identifier of the team. Autogenerated.", example = "1")
    private Integer id;

    @Schema(description = "Name of the team. Must be unique, not blank, and cannot exceed 50 characters.", example = "Development Team")
    @NotBlank(message = "Team name cannot be blank (empty or whitespace)")
    @Size(max = 50, message = "Team name cannot exceed 50 characters")
    private String name;
}
